<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Condition="'$(PDFsharpBuildFewerFrameworks)'=='true'">
    <IsProjectBuildable>false</IsProjectBuildable>
  </PropertyGroup>

  <Target Name="CheckIfBuildable" BeforeTargets="BeforeBuild">
    <Message Text="Skipping build for $(MSBuildProjectName)" Importance="High" Condition="'$(IsProjectBuildable)' == 'false'" />
    <Error Text="Skipping build. Project does not support .NET 6/8 yet." Condition="'$(IsProjectBuildable)' == 'false'" />
  </Target>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <!--<TargetFrameworks>$(PDFsharpTargetFrameworks_Windows)</TargetFrameworks>-->
    <TargetFrameworks>net462</TargetFrameworks> 
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <DefineConstants>GDI</DefineConstants>
    <EnableWindowsTargeting>True</EnableWindowsTargeting>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
  </PropertyGroup>

  <ItemGroup Condition="'$(PDFsharpBuildFewerFrameworks)'!='true'">
    <PackageReference Include="$(PDFsharp_PSGDI_PackageName)" />
    <PackageReference Include="System.Resources.Extensions" />
  </ItemGroup>

</Project>
