<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(PDFsharpTargetFrameworks_Exe)</TargetFrameworks>
    <DefineConstants>CORE</DefineConstants>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="$(PDFsharp_PS_PackageName)" />
  </ItemGroup>
</Project>