<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>$(PDFsharpTargetFrameworks_Windows)</TargetFrameworks>
    <DefineConstants>GDI</DefineConstants>
    <EnableWindowsTargeting>True</EnableWindowsTargeting>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\..\PDFsharp\src\TextLayout\Program.cs" Link="Program.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="$(PDFsharp_PSGDI_PackageName)" />
  </ItemGroup>

</Project>
