<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>$(PDFsharpTargetFrameworks_Exe)</TargetFrameworks>
    <DefineConstants>CORE</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="$(PDFsharp_PS_PackageName)" />
    <PackageReference Include="$(PDFsharp_PSMD_PackageName)" />
  </ItemGroup>

</Project>
