<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>$(PDFsharpTargetFrameworks_Library)</TargetFrameworks>
    <AssemblyName>SubstitutingFontResolver</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="$(PDFsharp_PS_PackageName)" />
  </ItemGroup>

</Project>
