<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>$(PDFsharpTargetFrameworks_Windows)</TargetFrameworks>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <UseWPF>true</UseWPF>
    <DefineConstants>WPF</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\..\PDFsharp\src\HelloWorld\Program.cs" Link="Program.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="$(PDFsharp_PSWPF_PackageName)" />
  </ItemGroup>

</Project>
